/*
 * AboutDialog.java
 *
 * Created on June 18, 2008, 6:14 AM
 */

package sanchay.gui.clients;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import sanchay.GlobalProperties;
import sanchay.common.types.ClientType;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author  Rahul
 */
public class AboutDialog extends javax.swing.JDialog {

    ClientType clientType=null;
    
    java.awt.Frame parent;
    
    /** Creates new form AboutDialog */
    
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.parent=parent;
                  
        initComponents();

        setTitle(GlobalProperties.getIntlString("About_Sanchay_"));

        BufferedImage image = null;

        try {
            image = javax.imageio.ImageIO.read(new File(GlobalProperties.getHomeDirectory() + "/" + "images/sanchay-logo.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        image = UtilityFunctions.getScaledInstance(image, logoJLabel.getWidth(), logoJLabel.getHeight(), UtilityFunctions.getDefaultConfiguration());

        ImageIcon icon = new ImageIcon(image, GlobalProperties.getIntlString("Sanchay"));

        logoJLabel.setIcon(icon);
        
        //versionjScrollPane.setVisible(false);
//        System.out.println("version removed?");
        this.pack();
        
        //this.validate();
        
        
        
        
    }
    
    public AboutDialog(java.awt.Frame parent, boolean modal, ClientType ctype) {
        super(parent, modal);
        
        clientType = ctype;
        
        initComponents();
        String identity=ctype.toString();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoJLabel = new javax.swing.JLabel();
        textJScrollPane = new javax.swing.JScrollPane();
        textJTextPane = new javax.swing.JTextPane();
        versionjScrollPane = new javax.swing.JScrollPane();
        version = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        setTitle(bundle.getString("About")); // NOI18N

        textJTextPane.setBackground(getBackground());
        textJTextPane.setBorder(null);
        textJTextPane.setEditable(false);
        textJTextPane.setFont(new java.awt.Font("Serif", 1, 12));
        textJTextPane.setText(bundle.getString("Sanchay_is_a_collection_of_tools_and_APIs_for_Natural_Language_Processing_(NLP)_and_Computational_Linguistics_(CL),_specially_tailored_for_South_Asian_languages.")); // NOI18N
        textJScrollPane.setViewportView(textJTextPane);

        version.setColumns(20);
        version.setRows(5);
        version.setText("Version: 0.4.3\nUpdate 1.1\nRelease Date: 28th April, 2011");
        versionjScrollPane.setViewportView(version);
        version.getAccessibleContext().setAccessibleName(bundle.getString("version")); // NOI18N
        version.getAccessibleContext().setAccessibleDescription(bundle.getString("version")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versionjScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(textJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(versionjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public static JDialog createAboutJDialog(java.awt.Frame parent, boolean modal, ClientType ctype)
    {
        if(ctype == null)
            return new AboutDialog(parent, modal, ctype);
        else
        {
            
        }
        
        return null;
    }

    private void showApplicationAbout()
    {
        SubApplicationDescriptionJDialog showthis = new SubApplicationDescriptionJDialog(parent, true);
        showthis.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JScrollPane textJScrollPane;
    private javax.swing.JTextPane textJTextPane;
    public javax.swing.JTextArea version;
    private javax.swing.JScrollPane versionjScrollPane;
    // End of variables declaration//GEN-END:variables

}
