/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransliterationJPanel.java
 *
 * Created on 22 Jul, 2009, 6:33:50 AM
 */

package sanchay.mlearning.mt.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;
import sanchay.GlobalProperties;
import sanchay.gui.common.SanchayLanguages;
import sanchay.gui.common.JPanelDialog;
import sanchay.mlearning.mt.MLTransliterator;
import sanchay.util.UtilityFunctions;
import sanchay.common.types.ClientType;

/**
 *
 * @author Anil Kumar Singh
 */
public class TransliterationJPanel extends javax.swing.JPanel implements JPanelDialog, sanchay.gui.clients.SanchayClient {

    protected ClientType clientType = ClientType.LANGUAGE_ENCODING_IDENTIFIER;

    protected JFrame owner;
    protected JDialog dialog;
    protected Component parentComponent;

    private String langEnc = GlobalProperties.getIntlString("hin::utf8");
    protected String charset = GlobalProperties.getIntlString("UTF-8");

    protected String title = GlobalProperties.getIntlString("Transliteration");

    private DefaultComboBoxModel langauges;
    private DefaultComboBoxModel encodings;

    protected MLTransliterator mlLTransliterator;

    /** Creates new form TransliterationJPanel */
    public TransliterationJPanel() {
        initComponents();

        parentComponent = this;

        langauges = new DefaultComboBoxModel();
        encodings = new DefaultComboBoxModel();

        SanchayLanguages.fillLanguages(langauges);
        SanchayLanguages.fillEncodings(encodings, GlobalProperties.getIntlString("hin"));

        languageJComboBox.setModel(langauges);
        encodingJComboBox.setModel(encodings);

        charset = GlobalProperties.getIntlString("UTF-8");

        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadJPanel = new javax.swing.JPanel();
        lagEncJPanel = new javax.swing.JPanel();
        languageJPanel = new javax.swing.JPanel();
        languageJLabel = new javax.swing.JLabel();
        languageJComboBox = new javax.swing.JComboBox();
        encodingJPanel = new javax.swing.JPanel();
        encodingJLabel = new javax.swing.JLabel();
        encodingJComboBox = new javax.swing.JComboBox();
        setupJPanel = new javax.swing.JPanel();
        mainJPanel = new javax.swing.JPanel();
        mainJTabbedPane = new javax.swing.JTabbedPane();
        mainTransliterateJPanel = new javax.swing.JPanel();
        mainCommandsJPanel = new javax.swing.JPanel();
        transliterateJButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        loadJPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        lagEncJPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        languageJPanel.setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        languageJLabel.setText(bundle.getString("Language:_")); // NOI18N
        languageJPanel.add(languageJLabel, java.awt.BorderLayout.WEST);

        languageJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageJComboBoxActionPerformed(evt);
            }
        });
        languageJPanel.add(languageJComboBox, java.awt.BorderLayout.CENTER);

        lagEncJPanel.add(languageJPanel);

        encodingJPanel.setLayout(new java.awt.BorderLayout());

        encodingJLabel.setText(bundle.getString("Encoding:__")); // NOI18N
        encodingJPanel.add(encodingJLabel, java.awt.BorderLayout.WEST);

        encodingJPanel.add(encodingJComboBox, java.awt.BorderLayout.CENTER);

        lagEncJPanel.add(encodingJPanel);

        loadJPanel.add(lagEncJPanel);

        javax.swing.GroupLayout setupJPanelLayout = new javax.swing.GroupLayout(setupJPanel);
        setupJPanel.setLayout(setupJPanelLayout);
        setupJPanelLayout.setHorizontalGroup(
            setupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        setupJPanelLayout.setVerticalGroup(
            setupJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        loadJPanel.add(setupJPanel);

        add(loadJPanel, java.awt.BorderLayout.NORTH);

        mainJPanel.setLayout(new java.awt.BorderLayout());

        mainTransliterateJPanel.setToolTipText(bundle.getString("Main_transliterate_panel")); // NOI18N

        javax.swing.GroupLayout mainTransliterateJPanelLayout = new javax.swing.GroupLayout(mainTransliterateJPanel);
        mainTransliterateJPanel.setLayout(mainTransliterateJPanelLayout);
        mainTransliterateJPanelLayout.setHorizontalGroup(
            mainTransliterateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        mainTransliterateJPanelLayout.setVerticalGroup(
            mainTransliterateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        mainJTabbedPane.addTab(bundle.getString("Transliterate"), mainTransliterateJPanel); // NOI18N

        mainJPanel.add(mainJTabbedPane, java.awt.BorderLayout.CENTER);

        mainCommandsJPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        transliterateJButton.setText(bundle.getString("Transliterate")); // NOI18N
        transliterateJButton.setToolTipText(bundle.getString("Transliterate")); // NOI18N
        mainCommandsJPanel.add(transliterateJButton);

        mainJPanel.add(mainCommandsJPanel, java.awt.BorderLayout.SOUTH);

        add(mainJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void languageJComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_languageJComboBoxActionPerformed
    {//GEN-HEADEREND:event_languageJComboBoxActionPerformed
        // TODO add your handling code here:
        langEnc = (String) languageJComboBox.getSelectedItem();
        SanchayLanguages.fillEncodings(encodings, SanchayLanguages.getLanguageCode(langEnc));
}//GEN-LAST:event_languageJComboBoxActionPerformed

    protected void init()
    {
        mlLTransliterator = new MLTransliterator();
        mlLTransliterator.init();
    }

    public ClientType getClientType()
    {
        return clientType;
    }

    public String getLangEnc()
    {
        return langEnc;
    }

    public Frame getOwner() {
        return owner;
    }

    public void setOwner(Frame frame) {
        owner = (JFrame) frame;
    }

    public void setParentComponent(Component parentComponent)
    {
        this.parentComponent = parentComponent;
    }

    public void setDialog(JDialog dialog) {
        this.dialog = dialog;
    }

    public String getTitle() {
        return title;
    }

    public JMenuBar getJMenuBar() {
        return null;
    }

    public JPopupMenu getJPopupMenu() {
        return null;
    }

    public JToolBar getJToolBar() {
        return null;
    }

    private static void createAndShowGUI() {
        //Create and set up the window.
        JFrame frame = new JFrame(GlobalProperties.getIntlString("Transliteration"));
        UtilityFunctions.setComponentFont(frame, GlobalProperties.getIntlString("hin::utf8"));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create and set up the menu bar and content pane.
        TransliterationJPanel demo = new TransliterationJPanel();
        demo.setOpaque(true); //content panes must be opaque
        frame.setContentPane(demo);

        demo.setOwner(frame);

        //Display the window.
        frame.pack();

        int inset = 5;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setBounds(inset, inset,
                screenSize.width  - inset*2,
                screenSize.height - inset*9);

        frame.setVisible(true);

        demo.requestFocusInWindow();
    }

    public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox encodingJComboBox;
    private javax.swing.JLabel encodingJLabel;
    private javax.swing.JPanel encodingJPanel;
    private javax.swing.JPanel lagEncJPanel;
    private javax.swing.JComboBox languageJComboBox;
    private javax.swing.JLabel languageJLabel;
    private javax.swing.JPanel languageJPanel;
    private javax.swing.JPanel loadJPanel;
    private javax.swing.JPanel mainCommandsJPanel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JTabbedPane mainJTabbedPane;
    private javax.swing.JPanel mainTransliterateJPanel;
    private javax.swing.JPanel setupJPanel;
    private javax.swing.JButton transliterateJButton;
    // End of variables declaration//GEN-END:variables

}
