/*
 * FileFilterJPanel.java
 *
 * Created on May 17, 2006, 9:30 PM
 */

package sanchay.gui.common;

import javax.swing.*;

/**
 *
 * @author  anil
 */
public class FileFilterJPanel extends javax.swing.JPanel {

    protected JDialog dialog;
    
    /** Creates new form FileFilterJPanel */
    public FileFilterJPanel() {
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateButtonGroup = new javax.swing.ButtonGroup();
        mainJTabbedPane = new javax.swing.JTabbedPane();
        extensionJPanel = new javax.swing.JPanel();
        extensionJLabel = new javax.swing.JLabel();
        extensionJComboBox = new javax.swing.JComboBox();
        nameJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        nameJScrollPane = new javax.swing.JScrollPane();
        nameJTextArea = new javax.swing.JTextArea();
        langEncJPanel = new javax.swing.JPanel();
        languageJPanel = new javax.swing.JPanel();
        languageJLabel = new javax.swing.JLabel();
        languageJScrollPane = new javax.swing.JScrollPane();
        languageJList = new javax.swing.JList();
        encodingJPanel = new javax.swing.JPanel();
        encodingJLabel = new javax.swing.JLabel();
        encodingJScrollPane = new javax.swing.JScrollPane();
        encodingJList = new javax.swing.JList();
        formatJPanel = new javax.swing.JPanel();
        formatJLabel = new javax.swing.JLabel();
        formatJScrollPane = new javax.swing.JScrollPane();
        formatJList = new javax.swing.JList();
        sizeJPanel = new javax.swing.JPanel();
        minSizeJPanel = new javax.swing.JPanel();
        minSizeJLabel = new javax.swing.JLabel();
        minSizeJTextField = new javax.swing.JTextField();
        minSizeJComboBox = new javax.swing.JComboBox();
        maxSizeJPanel = new javax.swing.JPanel();
        maxSizeJLabel1 = new javax.swing.JLabel();
        maxSizeJTextField = new javax.swing.JTextField();
        maxSizeJComboBox = new javax.swing.JComboBox();
        timeJPanel = new javax.swing.JPanel();
        withinJPanel = new javax.swing.JPanel();
        withinJRadioButton = new javax.swing.JRadioButton();
        withinJTextField = new javax.swing.JTextField();
        daysJLabel = new javax.swing.JLabel();
        betweenJPanel = new javax.swing.JPanel();
        betweenJRadioButton = new javax.swing.JRadioButton();
        fromJDateChooser = new com.toedter.calendar.JDateChooser();
        andJLabel = new javax.swing.JLabel();
        toJDateChooser = new com.toedter.calendar.JDateChooser();
        fileDirJPanel = new javax.swing.JPanel();
        fileDirJLabel = new javax.swing.JLabel();
        fileDirJComboBox = new javax.swing.JComboBox();
        permissionsJPanel = new javax.swing.JPanel();
        permissionsJLabel = new javax.swing.JLabel();
        permissionsJComboBox = new javax.swing.JComboBox();
        commandsJPanel = new javax.swing.JPanel();
        okJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(0, 4));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        mainJTabbedPane.setToolTipText(bundle.getString("Select_filter_type")); // NOI18N

        extensionJPanel.setToolTipText(bundle.getString("Set_file_extension_filter")); // NOI18N
        extensionJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        extensionJLabel.setLabelFor(extensionJComboBox);
        extensionJLabel.setText(bundle.getString("File_Extensions_(comma_separated):_")); // NOI18N
        extensionJPanel.add(extensionJLabel);

        extensionJComboBox.setEditable(true);
        extensionJPanel.add(extensionJComboBox);

        mainJTabbedPane.addTab("Extention", extensionJPanel);

        nameJPanel.setToolTipText(bundle.getString("Set_file_name_filter")); // NOI18N
        nameJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nameJLabel.setLabelFor(nameJTextArea);
        nameJLabel.setText(bundle.getString("File_Name_(regular_expression):_")); // NOI18N
        nameJPanel.add(nameJLabel);

        nameJTextArea.setColumns(20);
        nameJTextArea.setRows(1);
        nameJScrollPane.setViewportView(nameJTextArea);

        nameJPanel.add(nameJScrollPane);

        mainJTabbedPane.addTab("Name", nameJPanel);

        langEncJPanel.setToolTipText(bundle.getString("Set_language-encoding_filter")); // NOI18N
        langEncJPanel.setLayout(new java.awt.BorderLayout());

        languageJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        languageJLabel.setLabelFor(languageJList);
        languageJLabel.setText(bundle.getString("File_Languages:_")); // NOI18N
        languageJPanel.add(languageJLabel);

        languageJList.setVisibleRowCount(3);
        languageJScrollPane.setViewportView(languageJList);

        languageJPanel.add(languageJScrollPane);

        langEncJPanel.add(languageJPanel, java.awt.BorderLayout.NORTH);

        encodingJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        encodingJLabel.setLabelFor(encodingJList);
        encodingJLabel.setText(bundle.getString("File_Encodings:__")); // NOI18N
        encodingJPanel.add(encodingJLabel);

        encodingJList.setVisibleRowCount(3);
        encodingJScrollPane.setViewportView(encodingJList);

        encodingJPanel.add(encodingJScrollPane);

        langEncJPanel.add(encodingJPanel, java.awt.BorderLayout.CENTER);

        mainJTabbedPane.addTab("Lang-Enc", langEncJPanel);

        formatJPanel.setToolTipText(bundle.getString("Set_file_format_filter")); // NOI18N
        formatJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        formatJLabel.setLabelFor(formatJList);
        formatJLabel.setText(bundle.getString("File_Format:_")); // NOI18N
        formatJPanel.add(formatJLabel);

        formatJList.setVisibleRowCount(3);
        formatJScrollPane.setViewportView(formatJList);

        formatJPanel.add(formatJScrollPane);

        mainJTabbedPane.addTab("Format", formatJPanel);

        sizeJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File Size: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        sizeJPanel.setToolTipText(bundle.getString("Set_file_size_filter")); // NOI18N
        sizeJPanel.setLayout(new java.awt.BorderLayout());

        minSizeJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        minSizeJLabel.setLabelFor(minSizeJTextField);
        minSizeJLabel.setText(bundle.getString("Minimum_File_Size:")); // NOI18N
        minSizeJPanel.add(minSizeJLabel);

        minSizeJTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        minSizeJPanel.add(minSizeJTextField);

        minSizeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KB", "MB", "GB" }));
        minSizeJComboBox.setSelectedIndex(1);
        minSizeJPanel.add(minSizeJComboBox);

        sizeJPanel.add(minSizeJPanel, java.awt.BorderLayout.NORTH);

        maxSizeJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        maxSizeJLabel1.setLabelFor(maxSizeJTextField);
        maxSizeJLabel1.setText(bundle.getString("Maximum_File_Size:")); // NOI18N
        maxSizeJPanel.add(maxSizeJLabel1);

        maxSizeJTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        maxSizeJPanel.add(maxSizeJTextField);

        maxSizeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KB", "MB", "GB" }));
        maxSizeJPanel.add(maxSizeJComboBox);

        sizeJPanel.add(maxSizeJPanel, java.awt.BorderLayout.CENTER);

        mainJTabbedPane.addTab("Size", sizeJPanel);

        timeJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File Last Modified", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        timeJPanel.setToolTipText(bundle.getString("Set_file_time_filter")); // NOI18N
        timeJPanel.setLayout(new java.awt.BorderLayout());

        withinJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dateButtonGroup.add(withinJRadioButton);
        withinJRadioButton.setMnemonic('W');
        withinJRadioButton.setSelected(true);
        withinJRadioButton.setText(bundle.getString("Within_last_")); // NOI18N
        withinJRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        withinJRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        withinJPanel.add(withinJRadioButton);

        withinJTextField.setText("30");
        withinJTextField.setPreferredSize(new java.awt.Dimension(60, 19));
        withinJPanel.add(withinJTextField);

        daysJLabel.setLabelFor(withinJTextField);
        daysJLabel.setText(bundle.getString("_days")); // NOI18N
        withinJPanel.add(daysJLabel);

        timeJPanel.add(withinJPanel, java.awt.BorderLayout.NORTH);

        betweenJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dateButtonGroup.add(betweenJRadioButton);
        betweenJRadioButton.setMnemonic('B');
        betweenJRadioButton.setText(bundle.getString("Between_")); // NOI18N
        betweenJRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        betweenJRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        betweenJPanel.add(betweenJRadioButton);

        fromJDateChooser.setPreferredSize(new java.awt.Dimension(160, 19));
        betweenJPanel.add(fromJDateChooser);

        andJLabel.setText(bundle.getString("_and_")); // NOI18N
        betweenJPanel.add(andJLabel);

        toJDateChooser.setPreferredSize(new java.awt.Dimension(160, 19));
        betweenJPanel.add(toJDateChooser);

        timeJPanel.add(betweenJPanel, java.awt.BorderLayout.CENTER);

        mainJTabbedPane.addTab("Time", timeJPanel);

        fileDirJPanel.setToolTipText(bundle.getString("Set_file/directory_filter")); // NOI18N
        fileDirJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fileDirJLabel.setLabelFor(fileDirJComboBox);
        fileDirJLabel.setText(bundle.getString("File_or_Directory:_")); // NOI18N
        fileDirJPanel.add(fileDirJLabel);

        fileDirJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Both", "Files", "Directories" }));
        fileDirJPanel.add(fileDirJComboBox);

        mainJTabbedPane.addTab("File/Dir", fileDirJPanel);

        permissionsJPanel.setToolTipText(bundle.getString("Set_file_permissions_filter")); // NOI18N
        permissionsJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        permissionsJLabel.setLabelFor(permissionsJComboBox);
        permissionsJLabel.setText(bundle.getString("File_Permissions:_")); // NOI18N
        permissionsJPanel.add(permissionsJLabel);

        permissionsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Read and Write", "Read", "Write", "Hidden" }));
        permissionsJPanel.add(permissionsJComboBox);

        mainJTabbedPane.addTab("Permissions", permissionsJPanel);

        add(mainJTabbedPane, java.awt.BorderLayout.CENTER);

        commandsJPanel.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        okJButton.setText(bundle.getString("OK")); // NOI18N
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        commandsJPanel.add(okJButton);

        cancelJButton.setText(bundle.getString("Cancel")); // NOI18N
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });
        commandsJPanel.add(cancelJButton);

        add(commandsJPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_okJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel andJLabel;
    protected javax.swing.JPanel betweenJPanel;
    protected javax.swing.JRadioButton betweenJRadioButton;
    protected javax.swing.JButton cancelJButton;
    protected javax.swing.JPanel commandsJPanel;
    protected javax.swing.ButtonGroup dateButtonGroup;
    protected javax.swing.JLabel daysJLabel;
    protected javax.swing.JLabel encodingJLabel;
    protected javax.swing.JList encodingJList;
    protected javax.swing.JPanel encodingJPanel;
    protected javax.swing.JScrollPane encodingJScrollPane;
    protected javax.swing.JComboBox extensionJComboBox;
    protected javax.swing.JLabel extensionJLabel;
    protected javax.swing.JPanel extensionJPanel;
    protected javax.swing.JComboBox fileDirJComboBox;
    protected javax.swing.JLabel fileDirJLabel;
    protected javax.swing.JPanel fileDirJPanel;
    protected javax.swing.JLabel formatJLabel;
    protected javax.swing.JList formatJList;
    protected javax.swing.JPanel formatJPanel;
    protected javax.swing.JScrollPane formatJScrollPane;
    protected com.toedter.calendar.JDateChooser fromJDateChooser;
    protected javax.swing.JPanel langEncJPanel;
    protected javax.swing.JLabel languageJLabel;
    protected javax.swing.JList languageJList;
    protected javax.swing.JPanel languageJPanel;
    protected javax.swing.JScrollPane languageJScrollPane;
    protected javax.swing.JTabbedPane mainJTabbedPane;
    protected javax.swing.JComboBox maxSizeJComboBox;
    protected javax.swing.JLabel maxSizeJLabel1;
    protected javax.swing.JPanel maxSizeJPanel;
    protected javax.swing.JTextField maxSizeJTextField;
    protected javax.swing.JComboBox minSizeJComboBox;
    protected javax.swing.JLabel minSizeJLabel;
    protected javax.swing.JPanel minSizeJPanel;
    protected javax.swing.JTextField minSizeJTextField;
    protected javax.swing.JLabel nameJLabel;
    protected javax.swing.JPanel nameJPanel;
    protected javax.swing.JScrollPane nameJScrollPane;
    protected javax.swing.JTextArea nameJTextArea;
    protected javax.swing.JButton okJButton;
    protected javax.swing.JComboBox permissionsJComboBox;
    protected javax.swing.JLabel permissionsJLabel;
    protected javax.swing.JPanel permissionsJPanel;
    protected javax.swing.JPanel sizeJPanel;
    protected javax.swing.JPanel timeJPanel;
    protected com.toedter.calendar.JDateChooser toJDateChooser;
    protected javax.swing.JPanel withinJPanel;
    protected javax.swing.JRadioButton withinJRadioButton;
    protected javax.swing.JTextField withinJTextField;
    // End of variables declaration//GEN-END:variables
    
}
