/*
 * DiscourseConnectiveTreeJPanel.java
 *
 * Created on June 11, 2008, 10:20 AM
 */

package sanchay.corpus.span;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.im.InputContext;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;
import sanchay.GlobalProperties;
import sanchay.gui.clients.SanchayClient;
import sanchay.gui.common.SanchayLanguages;
import sanchay.text.editor.gui.TextEditorJPanel;
import sanchay.util.UtilityFunctions;
import sanchay.common.types.ClientType;

/**
 *
 * @author  RAKESH
 */
public class SpanAnnotationJPanel extends javax.swing.JPanel
        implements SanchayClient , sanchay.gui.common.JPanelDialog {

    protected ClientType clientType = ClientType.LANGUAGE_ENCODING_IDENTIFIER;
    
    protected JFrame owner;
    protected JDialog dialog;
    protected Component parentComponent;

    protected String langEnc = GlobalProperties.getIntlString("hin::utf8");
    protected TextEditorJPanel textEditorJPanel;
    protected String textFile;

    public SpanArgOptionalJPanel discourseArgOptionalJPanel;    
    
    /** Creates new form DiscourseConnectiveTreeJPanel */
    public SpanAnnotationJPanel(String lancEnc) {
        this.langEnc = lancEnc;
        
        initComponents();

        parentComponent = this;
        
        textEditorJPanel = new TextEditorJPanel(lancEnc, null, null, TextEditorJPanel.DEFAULT_MODE);
        textEditorJPanel.showCommandButtons(false);
        textEditorJPanel.collapseLeftJTabbedPane();
//        textEditorJPanel = new TextEditorJPanel(lancEnc);
        
        discourseArgOptionalJPanel = new SpanArgOptionalJPanel(lancEnc, textEditorJPanel, this);        
        discourseArgOptionalJPanel.setOwner(getOwner());
        
//        discourseArgOptionalJPanel.setTextEditorJPanel(textEditorJPanel);
               
        mainJSplitPane.setLeftComponent(textEditorJPanel);
        mainJSplitPane.setRightComponent(discourseArgOptionalJPanel);
        mainJSplitPane.setDividerLocation(700);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJSplitPane = new javax.swing.JSplitPane();

        setLayout(new java.awt.BorderLayout());

        mainJSplitPane.setResizeWeight(1.0);
        mainJSplitPane.setOneTouchExpandable(true);
        add(mainJSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public ClientType getClientType()
    {
        return clientType;
    }

    public String getLangEnc()
    {
        return langEnc;
    }

    public Frame getOwner() {
        return owner;
    }

    public void setOwner(Frame f) {
        owner = (JFrame) f;
    }

    public void setParentComponent(Component parentComponent)
    {
        this.parentComponent = parentComponent;
    }

    public void setDialog(JDialog d) {
        dialog = d;
    }

    public String getTitle() {
        return textEditorJPanel.getTitle();
    }

    public JMenuBar getJMenuBar() {
        return null;
    }

    public JToolBar getJToolBar() {
        return null;
    }

    public JPopupMenu getJPopupMenu()
    {
        return null;
    }
    
    public SpanArgOptionalJPanel getConnectiveInfoJPanel() {
        return discourseArgOptionalJPanel;
    }
    
    /**
     * Create the GUI and show it.  For thread safety,
     * this method should be invoked from the
     * event-dispatching thread.
     */
    private static void createAndShowGUI() {
        //Create and set up the window.
        JFrame frame = new JFrame(GlobalProperties.getIntlString("Span_Annotation_Interface"));
        UtilityFunctions.setComponentFont(frame, GlobalProperties.getIntlString("hin::utf8"));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        InputContext imc = frame.getInputContext();
//        System.out.println("Input method selected: " + imc.selectInputMethod(new Locale("hi", "in", "Inscript")));

	String selectedLanguage = TextEditorJPanel.switchLanguageStatic(frame);

        //Create and set up the content pane.
	SpanAnnotationJPanel newContentPane = null;

	if(selectedLanguage == null || selectedLanguage .equals("") == true)
	    newContentPane = new SpanAnnotationJPanel(GlobalProperties.getIntlString("hin::utf8"));
	else
	{
	    newContentPane = new SpanAnnotationJPanel(SanchayLanguages.getLangEncCode(selectedLanguage));
	}
        //Create and set up the menu bar and content pane.
//        DiscourseAnnotationJPanel demo = new DiscourseAnnotationJPanel("hin::utf8");
        newContentPane.setOpaque(true); //content panes must be opaque
        frame.setContentPane(newContentPane);
        frame.addWindowListener(newContentPane.getConnectiveInfoJPanel());

        newContentPane.setOwner(frame);        

        //Display the window.
        frame.pack();
        
        int inset = 1;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setBounds(inset, inset,
		screenSize.width  - inset*2,
		screenSize.height - inset*9);

	frame.setVisible(true);
        
        newContentPane.requestFocusInWindow(); 
        
        frame.setVisible(true);
    }
    
     
        
    
private void connectiveJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_connectiveJTreeValueChanged


}//GEN-LAST:event_connectiveJTreeValueChanged


    public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSplitPane mainJSplitPane;
    // End of variables declaration//GEN-END:variables

}
