/*
 * DSFSearchJPanel.java
 *
 * Created on September 26, 2005, 10:39 PM
 */

package sanchay.resources.dsf.gui;

/**
 *
 * @author  anil
 */
public class DSFSearchJPanel extends javax.swing.JPanel {
    
    /** Creates new form DSFSearchJPanel */
    public DSFSearchJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
