/*
 * DSFTaskJPanel.java
 *
 * Created on September 26, 2005, 12:45 AM
 */

package sanchay.resources.dsf.gui;

/**
 *
 * @author  anil
 */
public class DSFTaskJPanel extends javax.swing.JPanel {
    
    /** Creates new form DSFTaskJPanel */
    public DSFTaskJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskJPanel = new javax.swing.JPanel();
        taskNameJLabel = new javax.swing.JLabel();
        taskNameJTextField = new javax.swing.JTextField();
        propertiesJButton = new javax.swing.JButton();
        configJPanel = new javax.swing.JPanel();
        configJLabel = new javax.swing.JLabel();
        configJTextField = new javax.swing.JTextField();
        configJButton = new javax.swing.JButton();
        dataJPanel = new javax.swing.JPanel();
        dataJLabel = new javax.swing.JLabel();
        dataJTextField = new javax.swing.JTextField();
        dataJButton = new javax.swing.JButton();
        changesJPanel = new javax.swing.JPanel();
        changesJLabel = new javax.swing.JLabel();
        changesJTextField = new javax.swing.JTextField();
        changesJButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        taskJPanel.setLayout(new java.awt.BorderLayout());

        taskNameJLabel.setLabelFor(taskNameJTextField);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        taskNameJLabel.setText(bundle.getString("Task_name")); // NOI18N
        taskJPanel.add(taskNameJLabel, java.awt.BorderLayout.NORTH);

        taskNameJTextField.setText(bundle.getString("Task_name")); // NOI18N
        taskJPanel.add(taskNameJTextField, java.awt.BorderLayout.CENTER);

        propertiesJButton.setText(bundle.getString("Properties")); // NOI18N
        taskJPanel.add(propertiesJButton, java.awt.BorderLayout.EAST);

        add(taskJPanel);

        configJPanel.setLayout(new java.awt.BorderLayout());

        configJLabel.setLabelFor(configJTextField);
        configJLabel.setText(bundle.getString("Configuration_file")); // NOI18N
        configJPanel.add(configJLabel, java.awt.BorderLayout.NORTH);

        configJTextField.setText(bundle.getString("Configuration_file")); // NOI18N
        configJPanel.add(configJTextField, java.awt.BorderLayout.CENTER);

        configJButton.setText(bundle.getString("Browse")); // NOI18N
        configJPanel.add(configJButton, java.awt.BorderLayout.EAST);

        add(configJPanel);

        dataJPanel.setLayout(new java.awt.BorderLayout());

        dataJLabel.setLabelFor(dataJTextField);
        dataJLabel.setText(bundle.getString("Data_file")); // NOI18N
        dataJPanel.add(dataJLabel, java.awt.BorderLayout.NORTH);

        dataJTextField.setText(bundle.getString("Data_file")); // NOI18N
        dataJPanel.add(dataJTextField, java.awt.BorderLayout.CENTER);

        dataJButton.setText(bundle.getString("Browse")); // NOI18N
        dataJPanel.add(dataJButton, java.awt.BorderLayout.EAST);

        add(dataJPanel);

        changesJPanel.setLayout(new java.awt.BorderLayout());

        changesJLabel.setText(bundle.getString("Changes_file")); // NOI18N
        changesJPanel.add(changesJLabel, java.awt.BorderLayout.NORTH);

        changesJTextField.setText(bundle.getString("Changes_file")); // NOI18N
        changesJPanel.add(changesJTextField, java.awt.BorderLayout.CENTER);

        changesJButton.setText(bundle.getString("Browse")); // NOI18N
        changesJPanel.add(changesJButton, java.awt.BorderLayout.EAST);

        add(changesJPanel);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changesJButton;
    private javax.swing.JLabel changesJLabel;
    private javax.swing.JPanel changesJPanel;
    private javax.swing.JTextField changesJTextField;
    private javax.swing.JButton configJButton;
    private javax.swing.JLabel configJLabel;
    private javax.swing.JPanel configJPanel;
    private javax.swing.JTextField configJTextField;
    private javax.swing.JButton dataJButton;
    private javax.swing.JLabel dataJLabel;
    private javax.swing.JPanel dataJPanel;
    private javax.swing.JTextField dataJTextField;
    private javax.swing.JButton propertiesJButton;
    private javax.swing.JPanel taskJPanel;
    private javax.swing.JLabel taskNameJLabel;
    private javax.swing.JTextField taskNameJTextField;
    // End of variables declaration//GEN-END:variables
    
}
