/*
 * CorpusManagerJFrame.java
 *
 * Created on October 27, 2005, 4:43 PM
 */

package sanchay.corpus.manager.gui;

import java.awt.Component;
import java.awt.Frame;
import java.io.*;
import javax.swing.*;
import sanchay.gui.*;
import sanchay.gui.clients.AnnotationClient;
import sanchay.common.types.ClientType;

import sanchay.properties.*;


/**
 *
 * @author  anil
 */
public class CorpusManagerMain extends javax.swing.JFrame implements AnnotationClient {

    protected ClientType clientType = ClientType.LANGUAGE_ENCODING_IDENTIFIER;

   private JPanel corpusJPanel;
    
    private String workspace;
    private PropertiesManager propman;

    private String langEnc = sanchay.GlobalProperties.getIntlString("hin::utf8");
    
    private int currentPosition;
    
    /** Creates new form CorpusManagerJFrame */
    public CorpusManagerMain() {
        setTitle(sanchay.GlobalProperties.getIntlString("Corpus_Manager"));
        initComponents();

        corpusJPanel = new SelectTaskJPanel(SelectTaskJPanel.PARALLEL_MARKUP_TASK);
        corpusJPanel.setBounds(0, 0, 550, 130);
        desktopPane.add(corpusJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setBounds(250, 300, 558, 130);
//        currentJPanel.setVisible(true);

//        configure("workspace/tam-marker/server-props.txt", "UTF-8");
        ((SelectTaskJPanel) corpusJPanel).setOwner(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        fileMenu.setText(bundle.getString("File")); // NOI18N

        openMenuItem.setText(bundle.getString("Open")); // NOI18N
        fileMenu.add(openMenuItem);

        saveMenuItem.setText(bundle.getString("Save")); // NOI18N
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText(bundle.getString("Save_As_...")); // NOI18N
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText(bundle.getString("Exit")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText(bundle.getString("Edit")); // NOI18N

        cutMenuItem.setText(bundle.getString("Cut")); // NOI18N
        editMenu.add(cutMenuItem);

        copyMenuItem.setText(bundle.getString("Copy")); // NOI18N
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText(bundle.getString("Paste")); // NOI18N
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText(bundle.getString("Delete")); // NOI18N
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText(bundle.getString("Help")); // NOI18N

        contentMenuItem.setText(bundle.getString("Contents")); // NOI18N
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setText(bundle.getString("About")); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    public ClientType getClientType()
    {
        return clientType;
    }
    
    public String getWorkspace()
    {
        return workspace;
    }
    
    public void setWorkspace(String p) throws Exception
    {
        workspace = p;
        File wsdir = new File(p);

        if(wsdir.exists() == false)
        {
            if(wsdir.mkdir() == false)
                throw new Exception();
        }
        else if(wsdir.isDirectory() == false)
        throw new Exception();
    }
     
    public void setCurrentPosition(int cp)
    {
        currentPosition = cp;
    }
	
    public PropertiesManager getPropertiesManager()
    {
        return propman;
    }
    
    public void configure(String pmPath, String charSet)
    {
        clear();
        
        try {
            propman = new PropertiesManager(pmPath, charSet);
            propman.print(System.out);
            
            
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public void setWorkJPanel(JPanel wjp)
    {
        
    }
    
    public void clear()
    {
        workspace = "/home/anil/myproj/sanchay/eclipse/Sanchay/";
    }
  
    public PropertiesTable getTaskList()
    {
        return null;
    }
    
    public void setTaskList(PropertiesTable tl)
    {
        
    }

    public String getLangEnc()
    {
        return langEnc;
    }

    public Frame getOwner() {
        return this;
    }

    public void setOwner(Frame frame) {
    }

    public void setParentComponent(Component parentComponent)
    {
    }

    public JMenuBar getJMenuBar() {
        return null;
    }

    public JToolBar getJToolBar() {
        return null;
    }

    public JPopupMenu getJPopupMenu()
    {
        return null;
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorpusManagerMain().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem aboutMenuItem;
    public javax.swing.JMenuItem contentMenuItem;
    public javax.swing.JMenuItem copyMenuItem;
    public javax.swing.JMenuItem cutMenuItem;
    public javax.swing.JMenuItem deleteMenuItem;
    public javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu editMenu;
    public javax.swing.JMenuItem exitMenuItem;
    public javax.swing.JMenu fileMenu;
    public javax.swing.JMenu helpMenu;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem openMenuItem;
    public javax.swing.JMenuItem pasteMenuItem;
    public javax.swing.JMenuItem saveAsMenuItem;
    public javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
    
}
