/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AttributeValueJPanel.java
 *
 * Created on 13 Sep, 2009, 3:54:58 PM
 */

package sanchay.propbank.gui;

import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import sanchay.GlobalProperties;
import sanchay.corpus.ssf.features.FeatureAttribute;
import sanchay.corpus.ssf.features.FeatureStructure;
import sanchay.corpus.ssf.features.FeatureValue;
import sanchay.propbank.Frameset;
import sanchay.properties.MultiPropertyTokens;
import sanchay.properties.PropertyTokens;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author anil
 */
public class AttributeValueJPanel extends javax.swing.JPanel {

    protected String langEnc;

    protected String attrib;
    protected String value;

    protected FeatureStructure featureStructure;

    protected DefaultComboBoxModel options;

    /** Creates new form AttributeValueJPanel */
    public AttributeValueJPanel(String attrib, String value, String langEnc) {
        this.attrib = attrib;
        this.value = value;
        this.langEnc = langEnc;

        initComponents();

        init(attrib, value, null, langEnc);
    }

    public AttributeValueJPanel(String attrib, DefaultComboBoxModel options, String langEnc) {
        this.attrib = attrib;
        this.options = options;

        initComponents();

        init(attrib, null, options, langEnc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stringJPanel = new javax.swing.JPanel();
        stringJLabel = new javax.swing.JLabel();
        stringJTextField = new javax.swing.JTextField();
        optionsJPanel = new javax.swing.JPanel();
        optionsJLabel = new javax.swing.JLabel();
        optionsJComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.CardLayout());

        stringJPanel.setLayout(new java.awt.BorderLayout());

        stringJLabel.setPreferredSize(new java.awt.Dimension(100, 15));
        stringJPanel.add(stringJLabel, java.awt.BorderLayout.WEST);

        stringJTextField.setPreferredSize(new java.awt.Dimension(150, 19));
        stringJTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                stringJTextFieldCaretUpdate(evt);
            }
        });
        stringJPanel.add(stringJTextField, java.awt.BorderLayout.CENTER);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        add(stringJPanel, bundle.getString("String")); // NOI18N

        optionsJPanel.setLayout(new java.awt.BorderLayout());

        optionsJLabel.setPreferredSize(new java.awt.Dimension(100, 15));
        optionsJPanel.add(optionsJLabel, java.awt.BorderLayout.WEST);

        optionsJComboBox.setPreferredSize(new java.awt.Dimension(150, 24));
        optionsJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsJComboBoxActionPerformed(evt);
            }
        });
        optionsJPanel.add(optionsJComboBox, java.awt.BorderLayout.CENTER);

        add(optionsJPanel, bundle.getString("Options")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void stringJTextFieldCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_stringJTextFieldCaretUpdate
    {//GEN-HEADEREND:event_stringJTextFieldCaretUpdate
        // TODO add your handling code here:
        if(options == null && featureStructure != null)
        {
            value = stringJTextField.getText();
            featureStructure.addAttribute(attrib, value);
        }
    }//GEN-LAST:event_stringJTextFieldCaretUpdate

    private void optionsJComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_optionsJComboBoxActionPerformed
    {//GEN-HEADEREND:event_optionsJComboBoxActionPerformed
        // TODO add your handling code here:
        if(options != null && featureStructure != null)
        {
            value = (String) optionsJComboBox.getSelectedItem();
            featureStructure.addAttribute(attrib, value);
        }
    }//GEN-LAST:event_optionsJComboBoxActionPerformed

    public void init(String attrib, String value, DefaultComboBoxModel opts, String langEnc)
    {
        options = opts;

        MultiPropertyTokens attributeValues = Frameset.getAttributeValues();

        PropertyTokens values = attributeValues.getPropertiesValue(attrib);

        if(values != null && options == null)
        {
            options = PropertyTokens.getListModel(values);
        }

        if(options == null)
        {
            stringJLabel.setText(attrib);
            stringJTextField.setText(value);

            ((CardLayout) getLayout()).show(this, GlobalProperties.getIntlString("String"));

            UtilityFunctions.setComponentFont(stringJTextField, langEnc);
        }
        else
        {
            optionsJLabel.setText(attrib);
            optionsJComboBox.setModel(options);

            if(value != null)
                optionsJComboBox.setSelectedItem(value);

            ((CardLayout) getLayout()).show(this, GlobalProperties.getIntlString("Options"));

            UtilityFunctions.setComponentFont(stringJTextField, langEnc);
            UtilityFunctions.setComponentFont(optionsJComboBox, langEnc);
        }
    }

    /**
     * @return the featureStructure
     */
    public FeatureStructure getFeatureStructure()
    {
        return featureStructure;
    }

    /**
     * @param featureStructure the featureStructure to set
     */
    public void setFeatureStructure(FeatureStructure featureStructure)
    {
        this.featureStructure = featureStructure;
    }

    /**
     * @return the attrib
     */
    public String getAttrib()
    {
        return attrib;
    }

    /**
     * @param attrib the attrib to set
     */
    public void setAttrib(String attrib)
    {
        this.attrib = attrib;
    }

    /**
     * @return the value
     */
    public String getValue()
    {
        if(options != null)
        {
            value = (String) optionsJComboBox.getSelectedItem();
        }
        else
            value = stringJTextField.getText();

        return value;
    }

    /**
     * @param value the value to set
     */
    public void setValue(String value)
    {
        this.value = value;
    }

    /**
     * @return the options
     */
    public DefaultComboBoxModel getOptions()
    {
        return options;
    }

    /**
     * @param options the options to set
     */
    public void setOptions(DefaultComboBoxModel options)
    {
        this.options = options;
    }

    public static void fillAttributeValues(JPanel attributeValuesJPanel, FeatureStructure fs, String langEnc)
    {
        if(fs != null)
        {
            int count = fs.countAttributes();

            for (int i = 0; i < count; i++)
            {
                FeatureAttribute fa = fs.getAttribute(i);

                String name = fa.getName();

                if(fa.countAltValues() > 0)
                {
                    FeatureValue fv = fa.getAltValue(0);
                    String val = "";

                    if(fv != null)
                        val = fv.getValue().toString();

                    AttributeValueJPanel attributeValueJPanel = new AttributeValueJPanel(name, val, langEnc);
                    attributeValueJPanel.setFeatureStructure(fs);
                    attributeValuesJPanel.add(attributeValueJPanel);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox optionsJComboBox;
    private javax.swing.JLabel optionsJLabel;
    private javax.swing.JPanel optionsJPanel;
    private javax.swing.JLabel stringJLabel;
    private javax.swing.JPanel stringJPanel;
    private javax.swing.JTextField stringJTextField;
    // End of variables declaration//GEN-END:variables

}
