/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramesetExampleJPanel.java
 *
 * Created on 13 Sep, 2009, 3:34:07 PM
 */

package sanchay.propbank.gui;

import java.awt.event.MouseListener;
import java.util.EventObject;
import sanchay.GlobalProperties;
import sanchay.corpus.ssf.features.FeatureStructure;
import sanchay.corpus.ssf.features.FeatureValue;
import sanchay.propbank.FramesetAtom;
import sanchay.propbank.FramesetExample;
import sanchay.propbank.FramesetExampleArgument;
import sanchay.propbank.FramesetExampleInflections;
import sanchay.propbank.FramesetExampleRelation;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author anil
 */
public class FramesetExampleJPanel extends javax.swing.JPanel {

    protected String langEnc = GlobalProperties.getIntlString("hin::utf8");

    protected FramesetExample example;

    protected FramesetExampleArgumentJPanel argRelJPanel;

    /** Creates new form FramesetExampleJPanel */
    public FramesetExampleJPanel(String langEnc) {
        initComponents();

        this.langEnc = langEnc;
    }

    /**
     * @return the example
     */
    public FramesetExample getExample()
    {
        return example;
    }

    /**
     * @param example the example to set
     */
    public void setExample(FramesetExample example)
    {
        this.example = example;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topJPanel = new javax.swing.JPanel();
        exampleNoteJPanel = new javax.swing.JPanel();
        exampleNoteJScrollPane = new javax.swing.JScrollPane();
        exampleNoteJTextArea = new javax.swing.JTextArea();
        attribInflectionsJPanel = new javax.swing.JPanel();
        attribsJPanel = new javax.swing.JPanel();
        inflectionsJPanel = new javax.swing.JPanel();
        textJScrollPane = new javax.swing.JScrollPane();
        textJTextArea = new javax.swing.JTextArea();
        argumentsJScrollPane = new javax.swing.JScrollPane();
        argumentsJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout(0, 5));

        topJPanel.setLayout(new java.awt.BorderLayout(0, 5));

        exampleNoteJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Note"));
        exampleNoteJPanel.setLayout(new java.awt.BorderLayout());

        exampleNoteJTextArea.setColumns(20);
        exampleNoteJTextArea.setRows(2);
        exampleNoteJTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                exampleNoteJTextAreaCaretUpdate(evt);
            }
        });
        exampleNoteJScrollPane.setViewportView(exampleNoteJTextArea);

        exampleNoteJPanel.add(exampleNoteJScrollPane, java.awt.BorderLayout.CENTER);

        topJPanel.add(exampleNoteJPanel, java.awt.BorderLayout.NORTH);

        attribInflectionsJPanel.setLayout(new java.awt.BorderLayout(0, 5));

        attribsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Attributes"));
        attribsJPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        attribInflectionsJPanel.add(attribsJPanel, java.awt.BorderLayout.NORTH);

        inflectionsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Inflections"));
        inflectionsJPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        attribInflectionsJPanel.add(inflectionsJPanel, java.awt.BorderLayout.CENTER);

        topJPanel.add(attribInflectionsJPanel, java.awt.BorderLayout.CENTER);

        add(topJPanel, java.awt.BorderLayout.NORTH);

        textJTextArea.setColumns(20);
        textJTextArea.setRows(5);
        textJTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textJTextAreaCaretUpdate(evt);
            }
        });
        textJScrollPane.setViewportView(textJTextArea);

        add(textJScrollPane, java.awt.BorderLayout.CENTER);

        argumentsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Arguments"));
        argumentsJPanel.setLayout(new javax.swing.BoxLayout(argumentsJPanel, javax.swing.BoxLayout.Y_AXIS));
        argumentsJScrollPane.setViewportView(argumentsJPanel);

        add(argumentsJScrollPane, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void exampleNoteJTextAreaCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_exampleNoteJTextAreaCaretUpdate
    {//GEN-HEADEREND:event_exampleNoteJTextAreaCaretUpdate
        // TODO add your handling code here:
        example.setNote(exampleNoteJTextArea.getText());
    }//GEN-LAST:event_exampleNoteJTextAreaCaretUpdate

    private void textJTextAreaCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_textJTextAreaCaretUpdate
    {//GEN-HEADEREND:event_textJTextAreaCaretUpdate
        // TODO add your handling code here:
        example.setText(textJTextArea.getText());
    }//GEN-LAST:event_textJTextAreaCaretUpdate

    public void init()
    {
        UtilityFunctions.setComponentFont(exampleNoteJTextArea, langEnc);
        UtilityFunctions.setComponentFont(textJTextArea, langEnc);

        String note = example.getNote();
        exampleNoteJTextArea.setText(note);

        FeatureStructure fs = example.getAttributes();

        if(fs != null)
        {
            FeatureValue fv = fs.getAttributeValue(GlobalProperties.getIntlString("name"));
            String name = "";

            if(fv != null)
                name = fv.getValue().toString();

            AttributeValueJPanel attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("name"), name, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("type"));
            String type = "";

            if(fv != null)
                type = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("type"), type, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("src"));
            String src = "";

            if(fv != null)
                src = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("src"), src, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);
        }

        FramesetExampleInflections inflections = example.getInflections();
        
        fs = inflections.getAttributes();

        if(fs != null)
        {
            FeatureValue fv = fs.getAttributeValue(GlobalProperties.getIntlString("person"));
            String person = "";

            if(fv != null)
                person = fv.getValue().toString();

            AttributeValueJPanel attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("person"), person, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            inflectionsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("tense"));
            String tense = "";

            if(fv != null)
                tense = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("tense"), tense, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            inflectionsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("aspect"));
            String aspect = "";

            if(fv != null)
                aspect = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("aspect"), aspect, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            inflectionsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("voice"));

            String voice = "";

            if(fv != null)
                voice = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("voice"), voice, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            inflectionsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("form"));
            String form = "";

            if(fv != null)
                form = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("form"), form, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            inflectionsJPanel.add(attributeValueJPanel);
        }

        int count = getExample().countArguments();

        for (int i = 0; i < count; i++)
        {
            FramesetExampleArgument argument = getExample().getArgument(i);

            FramesetExampleArgumentJPanel argumentJPanel = new FramesetExampleArgumentJPanel(langEnc);
            argumentJPanel.setAtom(argument);
            argumentJPanel.init();

            argumentJPanel.setExamapleJPanel(this);

            argumentsJPanel.add(argumentJPanel);
        }

        count = getExample().countRelations();

        for (int i = 0; i < count; i++)
        {
            FramesetExampleRelation argument = getExample().getRelation(i);

            FramesetExampleArgumentJPanel argumentJPanel = new FramesetExampleArgumentJPanel(langEnc);
            argumentJPanel.setAtom(argument);
            argumentJPanel.init();

            argumentJPanel.setExamapleJPanel(this);

            argumentsJPanel.add(argumentJPanel);
        }

        String text = example.getText();
        textJTextArea.setText(text);

        setVisible(false);
        setVisible(true);
    }

    public void addArgument(EventObject e) {
        FramesetExampleArgument argument = new FramesetExampleArgument();
        example.addArgument(argument);

        FramesetExampleArgumentJPanel argumentJPanel = new FramesetExampleArgumentJPanel(langEnc);
        argumentJPanel.setExamapleJPanel(this);
        argumentJPanel.setAtom(argument);

        argumentJPanel.init();

        argumentsJPanel.add(argumentJPanel);

        setVisible(false);
        setVisible(true);
    }

    public void addRelation(EventObject e) {
        FramesetExampleRelation relation = new FramesetExampleRelation();
        example.addRelation(relation);

        FramesetExampleArgumentJPanel relationJPanel = new FramesetExampleArgumentJPanel(langEnc);
        relationJPanel.setExamapleJPanel(this);
        relationJPanel.setAtom(relation);

        relationJPanel.init();

        argumentsJPanel.add(relationJPanel);

        setVisible(false);
        setVisible(true);
    }

    public void removeArgument(FramesetExampleArgumentJPanel argumentJPanel)
    {
        FramesetAtom argument = argumentJPanel.getAtom();
        
        if(argument instanceof FramesetExampleArgument)
            example.removeArgument((FramesetExampleArgument) argument);
        else if(argument instanceof FramesetExampleRelation)
            example.removeRelation((FramesetExampleRelation) argument);

        argumentsJPanel.remove(argumentJPanel);

        setVisible(false);
        setVisible(true);
    }

    void addPopupListener(MouseListener l)
    {
        exampleNoteJPanel.addMouseListener(l);
        attribInflectionsJPanel.addMouseListener(l);
        textJTextArea.addMouseListener(l);
        argumentsJPanel.addMouseListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel argumentsJPanel;
    private javax.swing.JScrollPane argumentsJScrollPane;
    private javax.swing.JPanel attribInflectionsJPanel;
    private javax.swing.JPanel attribsJPanel;
    private javax.swing.JPanel exampleNoteJPanel;
    private javax.swing.JScrollPane exampleNoteJScrollPane;
    private javax.swing.JTextArea exampleNoteJTextArea;
    private javax.swing.JPanel inflectionsJPanel;
    private javax.swing.JScrollPane textJScrollPane;
    private javax.swing.JTextArea textJTextArea;
    private javax.swing.JPanel topJPanel;
    // End of variables declaration//GEN-END:variables

}
