/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramesetExampleArgumentJPanel.java
 *
 * Created on 16 Sep, 2009, 7:00:13 AM
 */

package sanchay.propbank.gui;

import sanchay.GlobalProperties;
import sanchay.corpus.ssf.features.FeatureStructure;
import sanchay.corpus.ssf.features.FeatureValue;
import sanchay.propbank.FramesetAtom;
import sanchay.propbank.FramesetExampleArgument;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author anil
 */
public class FramesetExampleArgumentJPanel extends javax.swing.JPanel {

    protected String langEnc = GlobalProperties.getIntlString("hin::utf8");

    protected FramesetAtom atom;

    protected FramesetExampleJPanel examapleJPanel;

    /** Creates new form FramesetExampleArgumentJPanel */
    public FramesetExampleArgumentJPanel(String langEnc) {
        initComponents();

        this.langEnc = langEnc;
    }

    /**
     * @return the atom
     */
    public FramesetAtom getAtom()
    {
        return atom;
    }

    /**
     * @param atom the atom to set
     */
    public void setAtom(FramesetAtom atom)
    {
        this.atom = atom;
    }

    public void init()
    {
        UtilityFunctions.setComponentFont(textJTextField, langEnc);

        String text = atom.getCData();
        textJTextField.setText(text);

        FeatureStructure fs = atom.getAttributes();

        FeatureValue fv = fs.getAttributeValue("\n");
        String n = "";

        if(fv != null)
            n = fv.getValue().toString();

        AttributeValueJPanel attributeValueJPanel = new AttributeValueJPanel("\n", n, langEnc);
        attributeValueJPanel.setFeatureStructure(fs);
        attribsJPanel.add(attributeValueJPanel);

        if(atom instanceof FramesetExampleArgument)
        {
            fv = fs.getAttributeValue(GlobalProperties.getIntlString("f"));
            String f = "";

            if(fv != null)
                f = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("f"), f, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);

            argTypeJLabel.setText(GlobalProperties.getIntlString("arg:_"));
        }
        else
            argTypeJLabel.setText(GlobalProperties.getIntlString("rel:_"));

        argumentsJPanel.setVisible(false);
        argumentsJPanel.setVisible(true);
    }

    /**
     * @return the examapleJPanel
     */
    public FramesetExampleJPanel getExamapleJPanel()
    {
        return examapleJPanel;
    }

    /**
     * @param examapleJPanel the examapleJPanel to set
     */
    public void setExamapleJPanel(FramesetExampleJPanel examapleJPanel)
    {
        this.examapleJPanel = examapleJPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        argumentsJPanel = new javax.swing.JPanel();
        argTypeJLabel = new javax.swing.JLabel();
        attribsJPanel = new javax.swing.JPanel();
        rightJPanel = new javax.swing.JPanel();
        textJPanel = new javax.swing.JPanel();
        textJTextField = new javax.swing.JTextField();
        commandsJPanel = new javax.swing.JPanel();
        removeJButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        argumentsJPanel.setLayout(new java.awt.BorderLayout());

        argTypeJLabel.setText("       ");
        argTypeJLabel.setPreferredSize(new java.awt.Dimension(45, 15));
        argumentsJPanel.add(argTypeJLabel, java.awt.BorderLayout.WEST);

        attribsJPanel.setPreferredSize(new java.awt.Dimension(30, 15));
        attribsJPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 5));
        argumentsJPanel.add(attribsJPanel, java.awt.BorderLayout.CENTER);

        add(argumentsJPanel);

        rightJPanel.setLayout(new java.awt.BorderLayout());

        textJPanel.setPreferredSize(new java.awt.Dimension(120, 35));
        textJPanel.setLayout(new java.awt.BorderLayout());

        textJTextField.setPreferredSize(new java.awt.Dimension(125, 19));
        textJTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textJTextFieldCaretUpdate(evt);
            }
        });
        textJPanel.add(textJTextField, java.awt.BorderLayout.CENTER);

        rightJPanel.add(textJPanel, java.awt.BorderLayout.CENTER);

        commandsJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        removeJButton.setText(bundle.getString("Remove")); // NOI18N
        removeJButton.setToolTipText(bundle.getString("Remove_VNRole")); // NOI18N
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        commandsJPanel.add(removeJButton);

        rightJPanel.add(commandsJPanel, java.awt.BorderLayout.EAST);

        add(rightJPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeJButtonActionPerformed
    {//GEN-HEADEREND:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        getExamapleJPanel().removeArgument(this);
}//GEN-LAST:event_removeJButtonActionPerformed

    private void textJTextFieldCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_textJTextFieldCaretUpdate
    {//GEN-HEADEREND:event_textJTextFieldCaretUpdate
        // TODO add your handling code here:
        atom.setCDataText(textJTextField.getText());
    }//GEN-LAST:event_textJTextFieldCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel argTypeJLabel;
    private javax.swing.JPanel argumentsJPanel;
    private javax.swing.JPanel attribsJPanel;
    private javax.swing.JPanel commandsJPanel;
    private javax.swing.JButton removeJButton;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JPanel textJPanel;
    private javax.swing.JTextField textJTextField;
    // End of variables declaration//GEN-END:variables

}
