/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramesetRoleJPanel.java
 *
 * Created on 13 Sep, 2009, 3:34:34 PM
 */

package sanchay.propbank.gui;

import com.wutka.dtd.DTD;
import sanchay.GlobalProperties;
import sanchay.corpus.ssf.features.FeatureStructure;
import sanchay.corpus.ssf.features.FeatureValue;
import sanchay.propbank.Frameset;
import sanchay.propbank.FramesetRole;
import sanchay.propbank.FramesetVNRole;

/**
 *
 * @author anil
 */
public class FramesetRoleJPanel extends javax.swing.JPanel {

    protected String langEnc = GlobalProperties.getIntlString("hin::utf8");
    
    protected FramesetRole role;

    protected FramesetRolesetJPanel framesetRolesetJPanel;

   /** Creates new form FramesetRoleJPanel */
    public FramesetRoleJPanel(String langEnc) {

        this.langEnc = langEnc;

        initComponents();
    }

    public void init()
    {
        FeatureStructure fs = getRole().getAttributes();

        DTD dtd = Frameset.getDTD();

        if(fs != null)
        {
            FeatureValue fv = fs.getAttributeValue("\n");
            String n = "";

            if(fv != null)
                n = fv.getValue().toString();
                
            AttributeValueJPanel attributeValueJPanel = new AttributeValueJPanel("\n", n, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("f"));
            String f = "";

            if(fv != null)
                f = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("f"), f, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("descr"));
            String descr = "";

            if(fv != null)
                descr = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("descr"), descr, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);
        }

        int count = getRole().countVNRoles();

        for (int i = 0; i < count; i++)
        {
            FramesetVNRole vnRole = getRole().getVNRole(i);

            FramesetVNRoleJPanel framesetVNRoleJPanel = new FramesetVNRoleJPanel(langEnc);
            framesetVNRoleJPanel.setVNRole(vnRole);
            framesetVNRoleJPanel.init();

            framesetVNRoleJPanel.setFramesetRoleJPanel(this);

            innerVNRolesJPanel.add(framesetVNRoleJPanel);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleTopJPanel = new javax.swing.JPanel();
        attribsJPanel = new javax.swing.JPanel();
        commandsJPanel = new javax.swing.JPanel();
        addVNRoleJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        vnRoleJSeparator = new javax.swing.JSeparator();
        vnRolesJPanel = new javax.swing.JPanel();
        innerVNRolesJPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Role"));
        setLayout(new java.awt.BorderLayout(0, 5));

        roleTopJPanel.setLayout(new java.awt.BorderLayout(5, 0));

        attribsJPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 5));
        roleTopJPanel.add(attribsJPanel, java.awt.BorderLayout.CENTER);

        commandsJPanel.setLayout(new java.awt.GridLayout(1, 0, 2, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        addVNRoleJButton.setText(bundle.getString("Add_VNRole")); // NOI18N
        addVNRoleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVNRoleJButtonActionPerformed(evt);
            }
        });
        commandsJPanel.add(addVNRoleJButton);

        removeJButton.setText(bundle.getString("Remove")); // NOI18N
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        commandsJPanel.add(removeJButton);

        roleTopJPanel.add(commandsJPanel, java.awt.BorderLayout.EAST);
        roleTopJPanel.add(vnRoleJSeparator, java.awt.BorderLayout.PAGE_END);

        add(roleTopJPanel, java.awt.BorderLayout.NORTH);

        vnRolesJPanel.setLayout(new java.awt.BorderLayout());

        innerVNRolesJPanel.setLayout(new javax.swing.BoxLayout(innerVNRolesJPanel, javax.swing.BoxLayout.Y_AXIS));
        vnRolesJPanel.add(innerVNRolesJPanel, java.awt.BorderLayout.NORTH);

        add(vnRolesJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the framesetRolesetJPanel
     */
    public FramesetRolesetJPanel getFramesetRolesetJPanel()
    {
        return framesetRolesetJPanel;
    }

    /**
     * @param framesetRolesetJPanel the framesetRolesetJPanel to set
     */
    public void setFramesetRolesetJPanel(FramesetRolesetJPanel framesetRolesetJPanel)
    {
        this.framesetRolesetJPanel = framesetRolesetJPanel;
    }

    private void addVNRoleJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addVNRoleJButtonActionPerformed
    {//GEN-HEADEREND:event_addVNRoleJButtonActionPerformed
        // TODO add your handling code here:
        FramesetVNRole vnRole = new FramesetVNRole();

        getRole().addVNRole(vnRole);

        FramesetVNRoleJPanel framesetVNRoleJPanel = new FramesetVNRoleJPanel(langEnc);
        framesetVNRoleJPanel.setVNRole(vnRole);
        framesetVNRoleJPanel.init();

        framesetVNRoleJPanel.setFramesetRoleJPanel(this);

        innerVNRolesJPanel.add(framesetVNRoleJPanel);

        setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_addVNRoleJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeJButtonActionPerformed
    {//GEN-HEADEREND:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        framesetRolesetJPanel.removeRole(this);
}//GEN-LAST:event_removeJButtonActionPerformed

    /**
     * @return the role
     */
    public FramesetRole getRole()
    {
        return role;
    }

    /**
     * @param role the role to set
     */
    public void setRole(FramesetRole role)
    {
        this.role = role;
    }

    public void removeVNRole(FramesetVNRoleJPanel framesetVNRoleJPanel) {
        FramesetVNRole vnrole = framesetVNRoleJPanel.getVNRole();
        role.removeVNRole(vnrole);

        innerVNRolesJPanel.remove(framesetVNRoleJPanel);

        setVisible(false);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVNRoleJButton;
    private javax.swing.JPanel attribsJPanel;
    private javax.swing.JPanel commandsJPanel;
    private javax.swing.JPanel innerVNRolesJPanel;
    private javax.swing.JButton removeJButton;
    private javax.swing.JPanel roleTopJPanel;
    private javax.swing.JSeparator vnRoleJSeparator;
    private javax.swing.JPanel vnRolesJPanel;
    // End of variables declaration//GEN-END:variables

}
