/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramesetRolesetJPanel.java
 *
 * Created on 13 Sep, 2009, 3:34:51 PM
 */

package sanchay.propbank.gui;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.MouseListener;
import java.util.EventObject;
import javax.swing.JDialog;
import javax.swing.JFrame;
import sanchay.GlobalProperties;
import sanchay.corpus.ssf.features.FeatureStructure;
import sanchay.corpus.ssf.features.FeatureValue;
import sanchay.gui.common.JPanelDialog;
import sanchay.gui.common.SanchayJDialog;
import sanchay.propbank.FramesetRole;
import sanchay.propbank.FramesetRoleset;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author anil
 */
public class FramesetRolesetJPanel extends javax.swing.JPanel {

    protected JFrame owner;
    protected JDialog dialog;

    protected String langEnc = GlobalProperties.getIntlString("hin::utf8");

    private FramesetRoleset roleset;

    /** Creates new form FramesetRolesetJPanel */
    public FramesetRolesetJPanel(String langEnc) {
        this.langEnc = langEnc;

        initComponents();
    }

    public void init()
    {
        UtilityFunctions.setComponentFont(rolesetNoteJTextArea, langEnc);
        UtilityFunctions.setComponentFont(rolesNoteJTextArea, langEnc);

        String notes = getRoleset().getNote();

        if(notes != null)
            rolesetNoteJTextArea.setText(notes);

        String rolesNotes = getRoleset().getRolesNote();

        if(rolesNotes != null)
            rolesNoteJTextArea.setText(rolesNotes);
        
        FeatureStructure fs = getRoleset().getAttributes();

        if(fs != null)
        {
            FeatureValue fv = fs.getAttributeValue(GlobalProperties.getIntlString("name"));
            String name = "";

            if(fv != null)
                name = fv.getValue().toString();

            AttributeValueJPanel attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("name"), name, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);

            fv = fs.getAttributeValue(GlobalProperties.getIntlString("vncls"));
            String vncls = "";

            if(fv != null)
                vncls = fv.getValue().toString();

            attributeValueJPanel = new AttributeValueJPanel(GlobalProperties.getIntlString("vncls"), vncls, langEnc);
            attributeValueJPanel.setFeatureStructure(fs);
            attribsJPanel.add(attributeValueJPanel);
        }

        int count = getRoleset().countRoles();

        for (int i = 0; i < count; i++)
        {
            FramesetRole role = getRoleset().getRole(i);

            FramesetRoleJPanel framesetRoleJPanel = new FramesetRoleJPanel(langEnc);
            framesetRoleJPanel.setRole(role);
            framesetRoleJPanel.init();

            framesetRoleJPanel.setFramesetRolesetJPanel(this);

            rolesJPanel.add(framesetRoleJPanel);
        }

        setVisible(false);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rolesetTopJPanel = new javax.swing.JPanel();
        rolesetNoteJScrollPane = new javax.swing.JScrollPane();
        rolesetNoteJTextArea = new javax.swing.JTextArea();
        rolesetJPanel = new javax.swing.JPanel();
        attribsJPanel = new javax.swing.JPanel();
        rolesJScrollPane = new javax.swing.JScrollPane();
        rolesJPanel = new javax.swing.JPanel();
        rolesNoteJScrollPane = new javax.swing.JScrollPane();
        rolesNoteJTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout(0, 5));

        rolesetTopJPanel.setLayout(new java.awt.BorderLayout());

        rolesetNoteJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Roleset Note"));

        rolesetNoteJTextArea.setColumns(20);
        rolesetNoteJTextArea.setRows(2);
        rolesetNoteJTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rolesetNoteJTextAreaCaretUpdate(evt);
            }
        });
        rolesetNoteJScrollPane.setViewportView(rolesetNoteJTextArea);

        rolesetTopJPanel.add(rolesetNoteJScrollPane, java.awt.BorderLayout.CENTER);

        add(rolesetTopJPanel, java.awt.BorderLayout.NORTH);

        rolesetJPanel.setLayout(new java.awt.BorderLayout(0, 5));

        attribsJPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        rolesetJPanel.add(attribsJPanel, java.awt.BorderLayout.NORTH);

        rolesJPanel.setLayout(new javax.swing.BoxLayout(rolesJPanel, javax.swing.BoxLayout.Y_AXIS));
        rolesJScrollPane.setViewportView(rolesJPanel);

        rolesetJPanel.add(rolesJScrollPane, java.awt.BorderLayout.CENTER);

        add(rolesetJPanel, java.awt.BorderLayout.CENTER);

        rolesNoteJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Roles Note"));

        rolesNoteJTextArea.setColumns(20);
        rolesNoteJTextArea.setRows(2);
        rolesNoteJTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rolesNoteJTextAreaCaretUpdate(evt);
            }
        });
        rolesNoteJScrollPane.setViewportView(rolesNoteJTextArea);

        add(rolesNoteJScrollPane, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void rolesetNoteJTextAreaCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_rolesetNoteJTextAreaCaretUpdate
    {//GEN-HEADEREND:event_rolesetNoteJTextAreaCaretUpdate
        // TODO add your handling code here:
        roleset.setNote(rolesetNoteJTextArea.getText());
    }//GEN-LAST:event_rolesetNoteJTextAreaCaretUpdate

    private void rolesNoteJTextAreaCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_rolesNoteJTextAreaCaretUpdate
    {//GEN-HEADEREND:event_rolesNoteJTextAreaCaretUpdate
        // TODO add your handling code here:
        roleset.setRolesNote(rolesNoteJTextArea.getText());
    }//GEN-LAST:event_rolesNoteJTextAreaCaretUpdate

    /**
     * @return the roleset
     */
    public FramesetRoleset getRoleset()
    {
        return roleset;
    }

    /**
     * @param roleset the roleset to set
     */
    public void setRoleset(FramesetRoleset roleset)
    {
        this.roleset = roleset;
    }

    public void addRole(EventObject e) {
        FramesetRole role = new FramesetRole();
        roleset.addRole(role);
        FramesetRoleJPanel framesetRoleJPanel = new FramesetRoleJPanel(langEnc);
        framesetRoleJPanel.setRole(role);
        framesetRoleJPanel.init();

        framesetRoleJPanel.setFramesetRolesetJPanel(this);

        rolesJPanel.add(framesetRoleJPanel);
    }

    public void removeRole(FramesetRoleJPanel framesetRoleJPanel) {
        FramesetRole role = framesetRoleJPanel.getRole();
        roleset.removeRole(role);

        rolesJPanel.remove(framesetRoleJPanel);

        setVisible(false);
        setVisible(true);
    }

    public void editExamples(EventObject e) {
        FramesetExamplesJPanel examplesJPanel = new FramesetExamplesJPanel(langEnc);

        if(owner != null)
            examplesJPanel.setOwner(owner);
        else if(dialog != null)
            examplesJPanel.setDialog(dialog);

        examplesJPanel.setRoleset(roleset);

        examplesJPanel.init();

        SanchayJDialog editJDialog = null;

        if(owner != null)
            editJDialog = new SanchayJDialog(owner, GlobalProperties.getIntlString("Edit_Examples"), true, (JPanelDialog) examplesJPanel);
        else if(dialog != null)
            editJDialog = new SanchayJDialog(dialog, GlobalProperties.getIntlString("Edit_Examples"), true, (JPanelDialog) examplesJPanel);

    	editJDialog.pack();

        int inset = 35;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        editJDialog.setBounds(inset, inset,
		screenSize.width  - inset*5,
		screenSize.height - inset*4);

    	UtilityFunctions.centre(editJDialog);

        editJDialog.setVisible(true);
    }

    public void setDialog(JDialog dialog)
    {
        this.dialog = dialog;
    }

    public void setOwner(Frame frame)
    {
        owner = (JFrame) frame;
    }

    void addPopupListener(MouseListener l)
    {
        rolesetNoteJScrollPane.addMouseListener(l);
        attribsJPanel.addMouseListener(l);
        rolesJPanel.addMouseListener(l);
        rolesNoteJScrollPane.addMouseListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attribsJPanel;
    private javax.swing.JPanel rolesJPanel;
    private javax.swing.JScrollPane rolesJScrollPane;
    private javax.swing.JScrollPane rolesNoteJScrollPane;
    private javax.swing.JTextArea rolesNoteJTextArea;
    private javax.swing.JPanel rolesetJPanel;
    private javax.swing.JScrollPane rolesetNoteJScrollPane;
    private javax.swing.JTextArea rolesetNoteJTextArea;
    private javax.swing.JPanel rolesetTopJPanel;
    // End of variables declaration//GEN-END:variables

}
