/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramesetPredicateJPanel.java
 *
 * Created on 13 Sep, 2009, 3:34:22 PM
 */

package sanchay.propbank.gui;

import java.awt.Frame;
import java.awt.event.MouseListener;
import java.util.EventObject;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanchay.GlobalProperties;
import sanchay.corpus.ssf.features.FeatureStructure;
import sanchay.corpus.ssf.features.FeatureValue;
import sanchay.propbank.FramesetPredicate;
import sanchay.propbank.FramesetRoleset;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author anil
 */
public class FramesetPredicateJPanel extends javax.swing.JPanel {

    protected JFrame owner;
    protected JDialog dialog;

    protected String langEnc = GlobalProperties.getIntlString("hin::utf8");

    private FramesetPredicate predicate;

    protected MouseListener popupListener;

    /** Creates new form FramesetPredicateJPanel */
    public FramesetPredicateJPanel(String langEnc) {
        this.langEnc = langEnc;

        initComponents();

        predicate = new FramesetPredicate();
    }

    public void init()
    {
        UtilityFunctions.setComponentFont(predicateNoteJTextArea, langEnc);

        String notes = getPredicate().getNote();
        
        if(notes != null)
            predicateNoteJTextArea.setText(notes);

        int count = getPredicate().countRolesets();

        for (int i = 0; i < count; i++)
        {
            FramesetRoleset roleset = getPredicate().getRoleset(i);
            FeatureStructure fs = roleset.getAttributes();

            if(fs != null)
            {
                FeatureValue fv = fs.getAttributeValue(GlobalProperties.getIntlString("id"));
                String id = "";

                if(fv != null)
                {
                    id = fv.getValue().toString();
                    FramesetRolesetJPanel framesetRolesetJPanel = new FramesetRolesetJPanel(langEnc);

                    if(owner != null)
                        framesetRolesetJPanel.setOwner(owner);
                    else if(dialog != null)
                        framesetRolesetJPanel.setDialog(dialog);

                    framesetRolesetJTabbedPane.add(id, framesetRolesetJPanel);

                    framesetRolesetJPanel.addPopupListener(popupListener);

                    framesetRolesetJPanel.setRoleset(roleset);
                    framesetRolesetJPanel.init();
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        predicateNoteJPanel = new javax.swing.JPanel();
        predicateNoteJScrollPane = new javax.swing.JScrollPane();
        predicateNoteJTextArea = new javax.swing.JTextArea();
        framesetRolesetJTabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        predicateNoteJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Predicate note"));
        predicateNoteJPanel.setLayout(new java.awt.BorderLayout());

        predicateNoteJTextArea.setColumns(20);
        predicateNoteJTextArea.setRows(2);
        predicateNoteJTextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                predicateNoteJTextAreaCaretUpdate(evt);
            }
        });
        predicateNoteJScrollPane.setViewportView(predicateNoteJTextArea);

        predicateNoteJPanel.add(predicateNoteJScrollPane, java.awt.BorderLayout.CENTER);

        add(predicateNoteJPanel, java.awt.BorderLayout.NORTH);
        add(framesetRolesetJTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void predicateNoteJTextAreaCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_predicateNoteJTextAreaCaretUpdate
    {//GEN-HEADEREND:event_predicateNoteJTextAreaCaretUpdate
        // TODO add your handling code here:
        predicate.setNote(predicateNoteJTextArea.getText());
    }//GEN-LAST:event_predicateNoteJTextAreaCaretUpdate

    /**
     * @return the predicate
     */
    public FramesetPredicate getPredicate()
    {
        return predicate;
    }

    /**
     * @param predicate the predicate to set
     */
    public void setPredicate(FramesetPredicate predicate)
    {
        this.predicate = predicate;
    }

    public void addRoleset(EventObject e) {
        FramesetRoleset roleset = new FramesetRoleset();

        predicate.addRoleset(roleset);

        FramesetRolesetJPanel framesetRolesetJPanel = new FramesetRolesetJPanel(langEnc);

        if(owner != null)
            framesetRolesetJPanel.setOwner(owner);
        else if(dialog != null)
            framesetRolesetJPanel.setDialog(dialog);

        framesetRolesetJPanel.setRoleset(roleset);
        framesetRolesetJPanel.init();

        framesetRolesetJTabbedPane.add(GlobalProperties.getIntlString("roleset"), framesetRolesetJPanel);

        framesetRolesetJPanel.addPopupListener(popupListener);
    }

    public void editRoleset(EventObject e) {
        if(framesetRolesetJTabbedPane.getTabCount() == 0)
            return;

        FramesetRolesetJPanel framesetRolesetJPanel = (FramesetRolesetJPanel) framesetRolesetJTabbedPane.getSelectedComponent();
        FramesetRoleset roleset = framesetRolesetJPanel.getRoleset();

        int index = framesetRolesetJTabbedPane.indexOfComponent(framesetRolesetJPanel);

        String rolesetId = JOptionPane.showInputDialog(GlobalProperties.getIntlString("Please_enter_the_roleset_id"), "");

        if(rolesetId != null && rolesetId.equals("") == false)
        {
            roleset.getAttributes().addAttribute(GlobalProperties.getIntlString("id"), rolesetId);
            framesetRolesetJTabbedPane.setTitleAt(index, rolesetId);
        }
    }

    public void removeRoleset(EventObject e) {
        FramesetRolesetJPanel framesetRolesetJPanel = (FramesetRolesetJPanel) framesetRolesetJTabbedPane.getSelectedComponent();
        FramesetRoleset roleset = framesetRolesetJPanel.getRoleset();
        predicate.removeRoleset(roleset);
        framesetRolesetJTabbedPane.remove(framesetRolesetJPanel);
    }

    public void addRole(EventObject e) {
        FramesetRolesetJPanel framesetRolesetJPanel = (FramesetRolesetJPanel) framesetRolesetJTabbedPane.getSelectedComponent();
        framesetRolesetJPanel.addRole(e);
    }

    public void editExamples(EventObject e) {
        FramesetRolesetJPanel framesetRolesetJPanel = (FramesetRolesetJPanel) framesetRolesetJTabbedPane.getSelectedComponent();

        if(owner != null)
            framesetRolesetJPanel.setOwner(owner);
        else if(dialog != null)
            framesetRolesetJPanel.setDialog(dialog);

        framesetRolesetJPanel.editExamples(e);
    }

    public void setDialog(JDialog dialog)
    {
        this.dialog = dialog;
    }

    public void setOwner(Frame frame)
    {
        owner = (JFrame) frame;
    }

    void addPopupListener(MouseListener l)
    {
        popupListener = l;
        
        predicateNoteJPanel.addMouseListener(l);
        framesetRolesetJTabbedPane.addMouseListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane framesetRolesetJTabbedPane;
    private javax.swing.JPanel predicateNoteJPanel;
    private javax.swing.JScrollPane predicateNoteJScrollPane;
    private javax.swing.JTextArea predicateNoteJTextArea;
    // End of variables declaration//GEN-END:variables

}
