/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsoleJPanel.java
 *
 * Created on 26 Oct, 2009, 2:08:51 PM
 */

package sanchay.gui.console;

import java.io.*;
import sanchay.util.UtilityFunctions;

/**
 *
 * @author anil
 */
public class ConsoleJPanel extends javax.swing.JPanel {

    protected String langEnc = "hin::utf8";
    protected String charset = "UTF-8";

    protected javax.swing.JScrollPane stdOutJScrollPane;
    protected javax.swing.JScrollPane stdErrJScrollPane;

    protected JTextConsole stdOutJTextConsole;
    protected JTextConsole stdErrJTextConsole;

    protected PipedInputStream piOut;
    protected PipedInputStream piErr;
    protected PipedOutputStream poOut;
    protected PipedOutputStream poErr;

    /** Creates new form ConsoleJPanel */
    public ConsoleJPanel() throws IOException {
        initComponents();

        stdOutJTextConsole = new JTextConsole();
        stdErrJTextConsole = new JTextConsole();

        stdOutJScrollPane = new javax.swing.JScrollPane();
        stdOutJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Output"));

        stdErrJScrollPane = new javax.swing.JScrollPane();
        stdErrJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Errors"));

        stdOutJScrollPane.setViewportView(stdOutJTextConsole);
        stdErrJScrollPane.setViewportView(stdErrJTextConsole);

        consoleJSplitPane.setTopComponent(stdOutJScrollPane);
        consoleJSplitPane.setBottomComponent(stdErrJScrollPane);

        piOut = new PipedInputStream();
        poOut = new PipedOutputStream(piOut);
//        System.setOut(new PrintStream(poOut, true, charset));

        // Set up System.err
        piErr = new PipedInputStream();
        poErr = new PipedOutputStream(piErr);
//        System.setErr(new PrintStream(poErr, true, charset));

        UtilityFunctions.setComponentFont(stdOutJTextConsole, langEnc);
        UtilityFunctions.setComponentFont(stdErrJTextConsole, langEnc);

        // Create reader threads
        new ConsoleReaderThread(piOut, stdOutJTextConsole).start();
        new ConsoleReaderThread(piErr, stdErrJTextConsole).start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consoleJSplitPane = new javax.swing.JSplitPane();

        setLayout(new java.awt.BorderLayout());

        consoleJSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        consoleJSplitPane.setResizeWeight(0.5);
        consoleJSplitPane.setOneTouchExpandable(true);
        add(consoleJSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane consoleJSplitPane;
    // End of variables declaration//GEN-END:variables

}
