/*
 * TaskSetup.java
 *
 * Created on November 16, 2005, 11:12 PM
 */

package sanchay.corpus.parallel.gui;
import java.io.*;
import java.util.*;
import javax.swing.*;

import sanchay.GlobalProperties;
import sanchay.common.types.*;
import sanchay.gui.*;
import sanchay.properties.KeyValueProperties;
import sanchay.properties.PropertiesManager;
import sanchay.properties.PropertiesTable;

/**
 *
 * @author  root
 */
public class TaskSetup extends javax.swing.JPanel implements TaskSetupJPanelInterface{
     
    private JFrame owner;
    private JDialog dialog;
    
    private String taskName;
    private String taskPropFile;

    private String srcCorpusFile;
    private String tgtCorpusFile;
    private String tgtCorpusUTF8File;

    private String srcTMFile;
    private String tgtTMFile;
    
    private KeyValueProperties taskKVP;
    private DefaultComboBoxModel taskList;
    
    private boolean newTask;

    /** Creates new form TaskSetup */
    public TaskSetup() {
        taskKVP = new KeyValueProperties();
        newTask = true;
        setVisible(true);
        initComponents();
        
    }

    public TaskSetup(KeyValueProperties kvp) {
        taskKVP = kvp;
        newTask = false;
        
        initComponents();

        configure();
        taskNameJTextField.setEditable(false);
        propJTextField.setEditable(false);
    }
    
    private void configure()
    {
        taskPropFile = taskKVP.getPropertyValue("TaskPropFile");

        srcCorpusFile = taskKVP.getPropertyValue("SLCorpusFile");
        tgtCorpusFile = taskKVP.getPropertyValue("TLCorpusFile");
        tgtCorpusUTF8File = taskKVP.getPropertyValue("TLCorpusUTF8File");
        
        propJTextField.setText(taskPropFile);
        srcCorpusJTextField.setText(srcCorpusFile);
        tgtCorpusJTextField.setText(tgtCorpusFile);
        tgtCorpusUTF8JTextField.setText(tgtCorpusUTF8File);
    }
     private String validateFileName(String fn)
    {
        SentenceAlignMain owner = (SentenceAlignMain) getOwner();
        String ws = owner.getWorkspace();
        
        if(fn.startsWith(File.separator) == true)
        {
            if(fn.startsWith(ws) == false)
            {
                JOptionPane.showMessageDialog(this, GlobalProperties.getIntlString("Files_should_be_in_the_workspace_directory:_") + ws, GlobalProperties.getIntlString("Error"), JOptionPane.ERROR_MESSAGE);
                return "";
            }
//            else
//            {
//                fn = taskPropFile.substring(ws.length());
//                fn.replaceFirst(ws, "");
   //                    fn.replaceFirst(ws, "");
//            }
        }
        
        return fn;
    }
    
    public JFrame getOwner()
    {
        return owner;
    }
    
    public void setOwner(JFrame f)
    {
        owner = f;
    }
    
    public void setDialog(JDialog d)
    {
        dialog = d;
    }
    
    public void setTaskList(DefaultComboBoxModel l)
    {
        taskList = l;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskJPanel = new javax.swing.JPanel();
        taskNameJLabel = new javax.swing.JLabel();
        taskNameJTextField = new javax.swing.JTextField();
        propJPanel = new javax.swing.JPanel();
        propJLabel = new javax.swing.JLabel();
        propJTextField = new javax.swing.JTextField();
        propertiesJButton = new javax.swing.JButton();
        srcCorpusJPanel = new javax.swing.JPanel();
        srcCorpusJLabel = new javax.swing.JLabel();
        srcCorpusJTextField = new javax.swing.JTextField();
        srcCorpusJButton = new javax.swing.JButton();
        tgtCorpusJPanel = new javax.swing.JPanel();
        tgtCorpusJLabel = new javax.swing.JLabel();
        tgtCorpusJTextField = new javax.swing.JTextField();
        tgtCorpusJButton = new javax.swing.JButton();
        tgtCorpusUTF8JPanel = new javax.swing.JPanel();
        tgtCorpusUTF8JLabel = new javax.swing.JLabel();
        tgtCorpusUTF8JTextField = new javax.swing.JTextField();
        tgtCorpusUTF8JButton = new javax.swing.JButton();
        srcTMListJPanel = new javax.swing.JPanel();
        srcTMListJLabel = new javax.swing.JLabel();
        srcTMListJTextField = new javax.swing.JTextField();
        srcTMListJButton = new javax.swing.JButton();
        tgtTMListJPanel = new javax.swing.JPanel();
        tgtTMListJLabel = new javax.swing.JLabel();
        tgtTMListJTextField = new javax.swing.JTextField();
        tgtTMListJButton = new javax.swing.JButton();
        commandsJPanel = new javax.swing.JPanel();
        OKJButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        taskJPanel.setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sanchay"); // NOI18N
        taskNameJLabel.setText(bundle.getString("Task_name:")); // NOI18N
        taskJPanel.add(taskNameJLabel, java.awt.BorderLayout.NORTH);

        taskNameJTextField.setText(bundle.getString("Task_name")); // NOI18N
        taskJPanel.add(taskNameJTextField, java.awt.BorderLayout.CENTER);

        add(taskJPanel);

        propJPanel.setLayout(new java.awt.BorderLayout());

        propJLabel.setText(bundle.getString("Task_properties_file:")); // NOI18N
        propJPanel.add(propJLabel, java.awt.BorderLayout.NORTH);

        propJTextField.setText(bundle.getString("Task_properties_file")); // NOI18N
        propJPanel.add(propJTextField, java.awt.BorderLayout.CENTER);

        propertiesJButton.setText(bundle.getString("Browse")); // NOI18N
        propertiesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertiesJButtonActionPerformed(evt);
            }
        });
        propJPanel.add(propertiesJButton, java.awt.BorderLayout.EAST);

        add(propJPanel);

        srcCorpusJPanel.setLayout(new java.awt.BorderLayout());

        srcCorpusJLabel.setText(bundle.getString("Source_corpus_file:")); // NOI18N
        srcCorpusJPanel.add(srcCorpusJLabel, java.awt.BorderLayout.NORTH);

        srcCorpusJTextField.setText(bundle.getString("Source_corpus_file")); // NOI18N
        srcCorpusJPanel.add(srcCorpusJTextField, java.awt.BorderLayout.CENTER);

        srcCorpusJButton.setText(bundle.getString("Browse")); // NOI18N
        srcCorpusJPanel.add(srcCorpusJButton, java.awt.BorderLayout.EAST);

        add(srcCorpusJPanel);

        tgtCorpusJPanel.setLayout(new java.awt.BorderLayout());

        tgtCorpusJLabel.setText(bundle.getString("Target_corpus_file:")); // NOI18N
        tgtCorpusJPanel.add(tgtCorpusJLabel, java.awt.BorderLayout.NORTH);

        tgtCorpusJTextField.setText(bundle.getString("Target_corpus_file")); // NOI18N
        tgtCorpusJPanel.add(tgtCorpusJTextField, java.awt.BorderLayout.CENTER);

        tgtCorpusJButton.setText(bundle.getString("Browse")); // NOI18N
        tgtCorpusJPanel.add(tgtCorpusJButton, java.awt.BorderLayout.EAST);

        add(tgtCorpusJPanel);

        tgtCorpusUTF8JPanel.setLayout(new java.awt.BorderLayout());

        tgtCorpusUTF8JLabel.setText(bundle.getString("Target_corpus_file_(UTF8):")); // NOI18N
        tgtCorpusUTF8JPanel.add(tgtCorpusUTF8JLabel, java.awt.BorderLayout.NORTH);

        tgtCorpusUTF8JTextField.setText(bundle.getString("Target_corpus_file_(UTF8)")); // NOI18N
        tgtCorpusUTF8JPanel.add(tgtCorpusUTF8JTextField, java.awt.BorderLayout.CENTER);

        tgtCorpusUTF8JButton.setText(bundle.getString("Browse")); // NOI18N
        tgtCorpusUTF8JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgtCorpusUTF8JButtonActionPerformed(evt);
            }
        });
        tgtCorpusUTF8JPanel.add(tgtCorpusUTF8JButton, java.awt.BorderLayout.EAST);

        add(tgtCorpusUTF8JPanel);

        srcTMListJPanel.setLayout(new java.awt.BorderLayout());

        srcTMListJLabel.setText(bundle.getString("Source_language_marker_file:")); // NOI18N
        srcTMListJPanel.add(srcTMListJLabel, java.awt.BorderLayout.NORTH);

        srcTMListJTextField.setText(bundle.getString("Source_language_marker_file")); // NOI18N
        srcTMListJPanel.add(srcTMListJTextField, java.awt.BorderLayout.CENTER);

        srcTMListJButton.setText(bundle.getString("Browse")); // NOI18N
        srcTMListJPanel.add(srcTMListJButton, java.awt.BorderLayout.EAST);

        add(srcTMListJPanel);

        tgtTMListJPanel.setLayout(new java.awt.BorderLayout());

        tgtTMListJLabel.setText(bundle.getString("Target_language_marker_file:")); // NOI18N
        tgtTMListJPanel.add(tgtTMListJLabel, java.awt.BorderLayout.NORTH);

        tgtTMListJTextField.setText(bundle.getString("Target_language_marker_file")); // NOI18N
        tgtTMListJPanel.add(tgtTMListJTextField, java.awt.BorderLayout.CENTER);

        tgtTMListJButton.setText(bundle.getString("Browse")); // NOI18N
        tgtTMListJPanel.add(tgtTMListJButton, java.awt.BorderLayout.EAST);

        add(tgtTMListJPanel);

        OKJButton.setText(bundle.getString("OK")); // NOI18N
        commandsJPanel.add(OKJButton);

        add(commandsJPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void tgtCorpusUTF8JButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgtCorpusUTF8JButtonActionPerformed
    {//GEN-HEADEREND:event_tgtCorpusUTF8JButtonActionPerformed
// TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           tgtCorpusUTF8File = chooser.getSelectedFile().getAbsolutePath();
           
//           if(validateFilePath(tgtCorpusUTF8File).equals("") == false)
//           {
               tgtCorpusUTF8JTextField.setText(tgtCorpusUTF8File);
//           }
        }
    }//GEN-LAST:event_tgtCorpusUTF8JButtonActionPerformed

    private void propertiesJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_propertiesJButtonActionPerformed
    {//GEN-HEADEREND:event_propertiesJButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_propertiesJButtonActionPerformed
    

    private boolean validateTaskName()
    {
        ParallelMarkupMain owner = (ParallelMarkupMain) getOwner();
        PropertiesManager pm = owner.getPropertiesManager();
        
        taskName = taskNameJTextField.getText();
        
        PropertiesTable tasks = (PropertiesTable) pm.getPropertyContainer("tasks", PropertyType.PROPERTY_TABLE);
        Vector rows = tasks.getRows("TaskName", taskName);
        
        if(rows.size() == 1)
        {
            JOptionPane.showMessageDialog(this, GlobalProperties.getIntlString("Task_name_alresdy_exists:_") + taskName, GlobalProperties.getIntlString("Error"), JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

    private boolean validateTaskPropsFilePath()
    {
        ParallelMarkupMain owner = (ParallelMarkupMain) getOwner();
        String ws = owner.getWorkspace();
        
        if(taskPropFile.startsWith(File.separator) == true)
        {
            if(taskPropFile.startsWith(ws) == false)
            {
                JOptionPane.showMessageDialog(this, GlobalProperties.getIntlString("Files_should_be_in_the_workspace_directory:_") + ws, GlobalProperties.getIntlString("Error"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
//            else
//            {
//                taskPropFile = taskPropFile.substring(ws.length());
//                taskPropFile.replaceFirst(ws, "");
//            }
        }
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKJButton;
    private javax.swing.JPanel commandsJPanel;
    private javax.swing.JLabel propJLabel;
    private javax.swing.JPanel propJPanel;
    private javax.swing.JTextField propJTextField;
    private javax.swing.JButton propertiesJButton;
    private javax.swing.JButton srcCorpusJButton;
    private javax.swing.JLabel srcCorpusJLabel;
    private javax.swing.JPanel srcCorpusJPanel;
    private javax.swing.JTextField srcCorpusJTextField;
    private javax.swing.JButton srcTMListJButton;
    private javax.swing.JLabel srcTMListJLabel;
    private javax.swing.JPanel srcTMListJPanel;
    private javax.swing.JTextField srcTMListJTextField;
    private javax.swing.JPanel taskJPanel;
    private javax.swing.JLabel taskNameJLabel;
    private javax.swing.JTextField taskNameJTextField;
    private javax.swing.JButton tgtCorpusJButton;
    private javax.swing.JLabel tgtCorpusJLabel;
    private javax.swing.JPanel tgtCorpusJPanel;
    private javax.swing.JTextField tgtCorpusJTextField;
    private javax.swing.JButton tgtCorpusUTF8JButton;
    private javax.swing.JLabel tgtCorpusUTF8JLabel;
    private javax.swing.JPanel tgtCorpusUTF8JPanel;
    private javax.swing.JTextField tgtCorpusUTF8JTextField;
    private javax.swing.JButton tgtTMListJButton;
    private javax.swing.JLabel tgtTMListJLabel;
    private javax.swing.JPanel tgtTMListJPanel;
    private javax.swing.JTextField tgtTMListJTextField;
    // End of variables declaration//GEN-END:variables
    
}
